
[project]
name = "proyectoGenerado"
version = "0.1.0"
description = "Proyecto generado autom√°ticamente"
authors = [{ name = "Estefania" }]
dependencies = []

[tool.pytest.ini_options]
pythonpath = ["src"]
    